# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    tags: [ '[0-9]+.[0-9]+.[0-9]+', '[0-9]+.[0-9]+.[0-9]+-[a-z]+' ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        # cache: yarn

    # - name: Install dependencies
    #   run: yarn install

    # - name: yarn_build
      # env:
      #   BASE_PATH: "/${{ github.event.repository.name }}"
      # run: |
      #   yarn run build

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go generate ./... && go build -ldflags="-s -w"

    # - name: Test
    #   run: go test -v ./...
